version: '3.8'

services:
  sqlserver-merchandise:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-merchandise
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password"
      # MSSQL_PID: "Developer"
    ports:
      - "1433:1433"

  ecommerce-app:
    image: mikaelarey/ecommerce.merchandise
    depends_on:
      - sqlserver-merchandise
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8080:80"
